# Generated by Django 5.2.6 on 2025-09-30 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('tires_ok', models.BooleanField(default=True, verbose_name='Pneus')),
                ('lights_ok', models.BooleanField(default=True, verbose_name='Luzes')),
                ('brakes_ok', models.BooleanField(default=True, verbose_name='Freios')),
                ('body_ok', models.BooleanField(default=True, verbose_name='Lataria')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['date'],
            },
        ),
    ]
