# Generated by Django 5.2.6 on 2025-09-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Quilometragem')),
                ('fuel_type', models.CharField(choices=[('GAS', 'Gasolina'), ('DSL', 'Diesel'), ('ETH', 'Etanol'), ('ELE', 'Eléctrico'), ('HYB', 'Híbrido')], default='GAS', max_length=3, verbose_name='Tipo de combustível')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['brand', 'model', 'year'],
            },
        ),
    ]
