# Generated by Django 5.2.6 on 2025-09-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('odometer', models.IntegerField(verbose_name='Odômetro')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Litros')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor total')),
                ('station_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posto')),
                ('receipt_photo_url', models.TextField(blank=True, null=True, verbose_name='receipt_photo_url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
                'ordering': ['-date'],
            },
        ),
    ]
